### ISSUE TITLE
Images not displaying whilst having them from the original exporter

### ISSUE THREAD

**Issue by Yeetster-cmd** [slatinsky/DiscordChatExporter-frontend#10]
So, I needed to save an entire DM, I downloaded DiscordChatExporter, that's fine and all, I ticked the Download Assets things, it downloaded the images just fine.

But then once I actually load up the JSON file in the frontend program, it doesn't find any of them, along with the pfp's (unlike the example guild which has both).

**Comment by slatinsky** [comment]
Hello,

based on your description it is not clear, what is happening. 

a) Is nginx (black box) running while you are using the frontend?
b) Does the folder path contain space?
c) did you move exported pictures to the exports folder? Or just json files? 
d) please delete folder `/dcef/backend/preprocess/temp` and run `RUN_VIEWER.bat` again
e) can you provide me with one message with assets from json? Can you confirm that the file exists in exports folder? 

Thanks

**Comment by Yeetster-cmd** [comment]
Was able to display them using the HTMl method, however none of what you suggested worked, it even broke it.

For a) yes it is running
For b)it does not, I tried it with and without
For c) I moved everything it gave me
For e) I cannot for privacy reasons but the files are indeed there, I checked quite a few.

**Comment by slatinsky** [comment]
@Quviresu I reproduced the issue and provided a fix in the latest release [v2.0.2](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v2.0.2)

I included registry tweak in the release and changed nginx config to not use `/../` in paths on Windows

**Comment by slatinsky** [comment]
Closing the issue as resolved. In case of problems with asset loading, reopen the issue

**Comment by apexorganism** [comment]
Well um I still have this issue. Ik there is a fix "FIX: Move DCEF to a folder with shorter path, e.g. C:\Users\User\Downloads\DiscordChatExporter-frontend-vX.Y.Z-win\ -> C:\DCEF\" However, I dont even know what dev meant by this
