### ISSUE TITLE
Media isn't showing up | TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by roperi** [slatinsky/DiscordChatExporter-frontend#12]
I'm getting this error when running the container: 

```
$ docker run --volume "$(pwd):/dcef/exports" --volume dcef_cache:/dcef/cache --rm -p 21011:21011 -it dcef
Running uncompiled version of preprocess.py
Found 24 JSON files
Found 4 HTML files

Found 2929 media files

Hash: 165f7eda972a09a2ec21e550665c76283ab113d340d02d1b431654836c757b10
Hash is different, cache is not up to date

Sorting JSONs by guild_id...
Traceback (most recent call last):
  File "/dcef/backend/preprocess/main.py", line 29, in <module>
    main(input_dir, output_dir)
  File "/dcef/backend/preprocess/main.py", line 15, in main
    p.process()
  File "/dcef/backend/preprocess/Preprocess.py", line 254, in process
    guild_id = helpers.pad_id(data['guild']['id'])
                              ~~~~~~~~~~~~~^^^^^^
TypeError: 'int' object is not subscriptable
```

**Comment by roperi** [comment]
This is what I did:

1. Clone and build
```
git clone https://github.com/slatinsky/DiscordChatExporter-frontend
cd DiscordChatExporter-frontend
docker build -t dcef .
```

2. I cd to the the folder that holds the json files (and their respective subfolders with media) which were created with DiscordChatExporter.Cli.

3. Ran the container and got the error shown in the post above.

I don't know if it has to do but media isn't showing up when navigating the Discord server/channels. But I can read all posts and texts (but no images).

This is how I exported the json with media.
`dotnet DiscordChatExporter.Cli.dll export -t $DISCORD_TOKEN -c $CHANNEL_ID -f Json -o /media/exports --media --reuse-media`

I got to say the first time i ran the container i hadn't downloaded the media. So I had to run the above command again but with --media --reuse-media. So i also wonder whether when I run container again it is reading from the cache created first time around when I hadn't downloaded any media but just the json files.

**Comment by roperi** [comment]
I also noticed that container tries to read 24 json files found in exports folder and its subfolders. But there are only 4 DiscordChatExporter exported channels. Now, within those channels' subfolders there are other 20 other json files which have nothing to do with DiscordChatExporter. Those other 20 json files are config files from another program and were posted and shared as attachments on the channels.

**Comment by roperi** [comment]
I deleted the json files found in the channels' subfolders and now DiscordChatexporter-frontend is showing all media! 

Yet the dcef shouldn't halt when parsing json files not related to DiscordChatExport.Cli when reading exports folder and its subfolders.


So this problem is very easy to replicate. Just put a random non-DiscordChatExporter.Cli json file inside the json media folder and it will break dcef.

**Comment by roperi** [comment]
Now, deleting Discord channels' users' own json files to make dcef work is not a solution at all, therefore I'll leave this issue open.  I still need to be able to see those json files when navigating the channel.

**Comment by slatinsky** [comment]
Hello,

thanks for the very detailed report.
Full code rewrite to client-server architecture is on the way in mongodb branch (not ready yet for the use, but it is almost finished).

This also explains issue #10. 

The new mongodb version already has better logic to detect only json files from DiscordChatExporter. But I think that it is not worth it to backport it to the old version, but it is better to just focus my (limited) time on finishing the new version. 

I will leave the issue open, because the bug is not fixed in the current version.

**Comment by roperi** [comment]
Thanks, @slatinsky ! The mongodb version sounds great!

**Comment by slatinsky** [comment]
The v2.0.0 version is released. It should fix your issue.

**Comment by slatinsky** [comment]
Closing the issue as solved in version 2. If you encounter any issues related to this one, please reopen the issue.
