### ISSUE TITLE
Hidden and empty filenames are not matched

### ISSUE THREAD

**Issue by rebane2001** [slatinsky/DiscordChatExporter-frontend#15]
When looking for local paths, glob ignores hidden files (eg `.foobar-ABCDE`) and the regex ignores empty filenames (`ABCDE`).

The first issue can be fixed by using the `include_hidden` glob keyword that was added in Python 3.11. However this would cause older Python versions to error, so the `TypeError` exception would need to be caught with a fallback that doesn't use the keyword.

I'm not sure what the best way to solve the empty filenames situation would be, possibly making the `strip_hash_from_filename` method return a generic string.

In practice, the hidden filenames sometimes occur when images are uploaded to discord and look something like `.eJwNxVEOgyAMANC7cAAKZQLxNgQJmmlLaM0-lt19v-4EED2.pqslNVLVEiec8IxkctgeUP5kocc`. The empty filenames sometimes occur for URL thumbnails.

**Comment by slatinsky** [comment]
Hello,

we are distributing the program in [Docker](https://github.com/slatinsky/DiscordChatExporter-frontend/blob/main/Dockerfile) and we already use python 3.11. And for windows, [compiled binaries ](https://github.com/slatinsky/DiscordChatExporter-frontend/blob/main/.github/workflows/windows-build.yml)  use python 3.11 too.
So using the newest python 3.11 features is not an issue here.

**Comment by Seb-135** [comment]
Adding onto this, it seems it isn't just empty file names (`ABCDE`), but any file name without an extension (`foobar-ABCDE`)
And I can confirm that this usually happens with URL thumbnails (there are several more examples of this in my exports):
![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/76539951/27017c52-4819-4c82-8879-706af8fa89fa)
![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/76539951/b9f56b3b-8a41-45bc-8596-5a1eecfd0380)

The image was definitely archived properly:
![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/76539951/8c582319-c74b-488a-a3fc-b2c2ea206dab)
![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/76539951/4de518fa-67c4-43cf-b515-9fe93a0471f0)

**Comment by rebane2001** [comment]
@Seb-135 I fixed extensionless files in #14, are you running a version with this fix in it?

**Comment by Seb-135** [comment]
@rebane2001 I can't seem to get the version I'm running beyond just "main", but I pulled DCEF from git for the first time today, so I'd imagine that would include the fix
