### ISSUE TITLE
Can't open guild backup with 2 million messages

### ISSUE THREAD

**Issue by Galo223344** [slatinsky/DiscordChatExporter-frontend#16]
## Expected Behavior

The guild is opened and you can browse its messages

## Actual Behavior

The program gets frozen on startup. After a while it unfreezes and you can click any guilds you have, but clicking on the big guild shows "500 Internal Error"

## Steps to reproduce the problem

  1. Add big guild to exports
  2. Wait for everything to be indexed
  3. Click on the guild

## Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?

  - [ ] Yes
  - [x] No

### Environment

  - Operating system: Windows 10 
  - CPU Architecture: x86_64 (PC) 
  - Type: Windows binary release
  - Ram: 16 GB

### DiscordChatExporter-frontend

  - Release version: v2.0.9

## Logs

Is there any relevant information in logs? If so, please provide them:

I don't think so. But here https://pastebin.com/xRZWujwJ

If you provide full logs, please make sure to remove any sensitive information from them.

**Comment by slatinsky** [comment]
I have checked the logs you provided, there is nothing out of the ordinary that I can see in those logs.

Does the 500 error message look like it was made by nginx?
![nginx500](https://user-images.githubusercontent.com/43640724/225809209-4b3636bc-68d3-4d87-9020-20a3727b285c.png)
If yes, can you please check, it there is anything useful in nginx error.log (`dcef/backend/nginx/logs/error.log`)?

**Comment by Galo223344** [comment]
After restarting the PC now it works, sorry!

Also, the error logs for Nginx were empty.
