### ISSUE TITLE
Messages Consisting of Only Emoji Should Render the Emoji Larger

### ISSUE THREAD

**Issue by Shadowmech88** [slatinsky/DiscordChatExporter-frontend#18]
Just a nitpick I noticed.
On Discord, when a message contains only emoji and no text, those emoji are larger than average. DCEF (at least the version 1.13.2 that I'm using) doesn't do this, instead displaying them at the same size they would be if there was text in the message.

Hopefully I'm not reporting something that's already been fixed in later versions. I couldn't find any issues about this, at least.

**Comment by slatinsky** [comment]
Implemented in [commit fa97ec0](https://github.com/slatinsky/DiscordChatExporter-frontend/commit/fa97ec0d3258d4c45db54df1700a99cea9c4e2ca)
