### ISSUE TITLE
Sortability options for channels and categories

### ISSUE THREAD

**Issue by MichelleMegurine** [slatinsky/DiscordChatExporter-frontend#20]
Hi! I love this front-end version, but it would be amazing if it showed the channels and categories in the original order (not alphabetically). Since the Exporter already shows them in the export options as originally sorted in Discord, I guess it's a front-end thing the fact that those are showing alphabetically. I tried renaming the json files by adding numbers to change the sorting view, but it didn't work (it keeps working and showing as previously).
It would be amazing if there was an option to sort the servers as preferred too.

**Comment by slatinsky** [comment]
The problem is that DiscordChatExporter doesn't export channel order. So we have three options:
1. Sort alphabetically
2. Sort by createdAt (we can calculate that from channel id, because id is discord snowflake)
3. Create external script to export guild info and use that file to sort channels correctly

**Comment by MichelleMegurine** [comment]
I think option 3 sounds great, but maybe being able to re-sort the "default" DiscordChatExporter version is better? And might work in servers too?
Like, importing from json as it is, then being able to re-sort in the front end as user pleases. And being able to save that info for the next time the front end opens.
(I'm a total ignorant in programming yet, so I might be asking impossibles or very difficult things without noticing).

**Comment by slatinsky** [comment]
I implemented another option in the [latest release 2.3.0](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v2.3.0) - sort them by message counts.
This way the most important channels stay on top.

The perfect solution would be the original order, but we don't have this information recorded in the exports.
