### ISSUE TITLE
Browser Memory Usage of Large Exports on Old Version

### ISSUE THREAD

**Issue by Shadowmech88** [slatinsky/DiscordChatExporter-frontend#21]
This is more of a question than a report.
On the old browser-based version (v1.13.2) is there any way to view very large exports (on the order of 2GB-3GB just for the JSON file)?
When I even mouse over the guild, Chrome kills the tab with an OOM error once it hits 1GB usage, and while Firefox actually does reach around 2.5GB usage, the page never opens and the memory usage quickly goes back to normal. Even if I navigate to the guild in Firefox via the URL, the page just remains solid white.

I assume the newer, non-browser-based version can handle this natively (as per #16) but it unfortunately won't run properly for me, so I'd like to know if it's possible to view such large exports even on the old version.
Do I need to use a partitioned export instead?

**Comment by slatinsky** [comment]
There is a way - move out some exports from `/exports` folder

v2 client-server rewrite already fixed this issue - client in this version requests only required data from the server

**Comment by slatinsky** [comment]
> Out of curiosity, does v2 still work this way when accessing the running instance via a web browser in the case of the Docker version? Or would I see similar OOM errors with even a recent release of the Docker version of DCEF?

v2 send to the client only message ids of the channel and only messages in the viewport are requested. That means that you can reach out of memory errors at some point, but you would need really really really large channel to reach that (unlikely).

**Comment by slatinsky** [comment]
Closing as won't fix. Memory usage is better in the latest version of frontend and it is not worth it to backport the change
