### ISSUE TITLE
Program Won't Run on Windows 7

### ISSUE THREAD

**Issue by Shadowmech88** [slatinsky/DiscordChatExporter-frontend#22]
I don't actually know if it's intended to run on Windows 7 at all, but I didn't see any OS version requirements listed anywhere.
I'm also just generally curious if it's _possible_ for it to run on Windows 7 with some additional user-side bandaids, even if it's not explicitly intended for it.

When I initially started the program, it complained about a missing `api-ms-win-core-path-l1-1-0.dll`, which I added to my system manually. After that, when I attempt to start it, Command Prompt opens and immediately closes with the message
> Error loading Python DLL: 'C:\Users\USERNAME\AppData\Local\Temp\_MEI123456\python311.dll'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.

The mentioned AppData folder always has a different numerical identifier, and none of the folders exist, although I notice similar folders do exist in the AppData folder of the Windows 10 PC where I run DCEF.

## Expected Behavior

The program would run.

## Actual Behavior

The program does not run.

## Steps to reproduce the problem

  1. Attempt to run the program.

### Environment

  - Operating system: Windows 7
  - CPU Architecture: x86_64 (PC)
  - Flavor: Windows binary release

### DiscordChatExporter-frontend

  - [Release](https://github.com/slatinsky/DiscordChatExporter-frontend/releases) version or commit hash: v2.1.1
  - Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?: No

### [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)

N/A: Tested with just the default guild.

## Logs

Is there any relevant information in logs? If so, please provide them:

No logs were generated at all.

**Comment by slatinsky** [comment]
True, the program won't run on Windows 7 (I have tested it). Windows 7 is end of life operating system and won't be supported.

That said, client side should run on Windows 7. But you will need to host the server on other computer.

**Comment by slatinsky** [comment]
Closing this issue, Windows 7 incompatibility is mentioned in docs now
