### ISSUE TITLE
Search not working correctly

### ISSUE THREAD

**Issue by signuppotter** [slatinsky/DiscordChatExporter-frontend#25]
Sometimes search doesn't jump to message correctly. Please check the video: https://streamable.com/bh1ola

**Comment by slatinsky** [comment]
Hello,
thanks for the report.

there are currently two issues with jump to message:
1. it won't jump, if you click jump on the same message second time. (your issue)
2. it won't jump, if the message you are trying to jump to is in the selected channel, but is too far (and not loaded).

It will be fixed. Workaround for now is to switch channel and click jump button again

**Comment by slatinsky** [comment]
Fixed in https://github.com/slatinsky/DiscordChatExporter-frontend/commit/19c607574ff0c07c267890640889b6333aa28da3
