### ISSUE TITLE
Extremely slow load times on Windows due to "Slow SessionWorkflow loop"

### ISSUE THREAD

**Issue by walllable** [slatinsky/DiscordChatExporter-frontend#31]
## Expected Behavior

DCEF starts faster, doesn't get hung up on specific steps as detailed below

## Actual Behavior

DCEF starts and outputs messages like `2023-07-16 22:52:09.447194  mongodb:        {"t":{"$date":"2023-07-16T22:52:09.447-04:00"},"s":"I",  "c":"EXECUTOR", "id":6983000, "ctx":"conn1","msg":"Slow SessionWorkflow loop","attr":{"elapsed":{"totalMillis":10000,"activeMillis":10000,"receiveWorkMillis":0,"processWorkMillis":10000,"sendResponseMillis":0,"finalizeMillis":0}}}` when processing JSONs. This could be a problem with how the JSONs got exported or something, I can provide some of them if need be.

## Steps to reproduce the problem

  1. Place provided .json exports in exports folder
  2. Start DCEF
  3.

## Specifications

Ryzen 5 5600
GTX 1080 ti
32 GB RAM

### Environment

  - Operating system: Windows 10
  - CPU Architecture: x86_64 (PC) 
  - Flavor: Windows binary release

### DiscordChatExporter-frontend

  - [Latest as of this issue's submit date, happened on the version before as well](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v2.4.0)
  - Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?: No (Seems to be my JSON files are weird in some way?)

### [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)

- Version (CLI `--version`): v2.40.0

How did you export the data?
  - Export format (CLI `--format`): Json
  - Downloaded assets (CLI `--media`): No
  - Markdown processing (CLI `--markdown`): No (or at least, I don't specify `--markdown`)
  - Other CLI options (optional): ...

  

## Logs

Is there any relevant information in logs? If so, please provide them:

Here's a snippet showing the messages, and how long they persist.
https://pastebin.com/hDh12K7v

**Comment by slatinsky** [comment]
Hello

**Comment by slatinsky** [comment]
If you think that the process is stuck, please reopen the issue.

There is a tradeoff between the speed of preprocessing and the RAM we need. There are people with gigabytes of export data - that just doesn't fit in their system RAM. I have chosen this speed tradeoff. The preprocessing is still 50-times faster than the time needed to export it from Discord.

**Comment by walllable** [comment]
Alright, noted - thanks for your time and the explanation, that makes sense to me.
