### ISSUE TITLE
Windows Defender detects the software is a trojan

### ISSUE THREAD

**Issue by eljestliv** [slatinsky/DiscordChatExporter-frontend#34]
The program gets detected as a trojan by Windows Defender.

It says this was detected:
Trojan:Win32/Bearfoos.A!ml

**Comment by slatinsky** [comment]
It's a false positive, you can read more in this discussion https://github.com/slatinsky/DiscordChatExporter-frontend/discussions/13

**Comment by slatinsky** [comment]
I updated docs in the main `README.md` - see FAQ. Closing the issue
