### ISSUE TITLE
how can i istall it on linux? 

### ISSUE THREAD

**Issue by Manni1000** [slatinsky/DiscordChatExporter-frontend#4]
sorry but i dont understand how i can install it on linux would be nice if i can get some help

**Comment by slatinsky** [comment]
Hello,

thanks for reporting an issue.

I added support for Linux users with Docker. Instructions how to run it are in readme:
[https://github.com/slatinsky/DiscordChatExporter-frontend#docker-version-linux](https://github.com/slatinsky/DiscordChatExporter-frontend#docker-version-linux)
