### ISSUE TITLE
Support for Discord-History-Tracker

### ISSUE THREAD

**Issue by hexahigh** [slatinsky/DiscordChatExporter-frontend#41]
Support for https://github.com/chylex/Discord-History-Tracker would be nice as it supports incremental backups

**Comment by slatinsky** [comment]
Hello, sorry this is outside the scope of the project. This viewer supports JSON exports created by DiscordChatExporter or other exporters (like [discordless](https://github.com/Roachbones/discordless/) exporting in the same format as DiscordChatExporter.

If someone will write concerter to convert chylex/Discord-History-Tracker format to DiscordChatExporter JSON format, I am happy to support it :)

**Comment by hexahigh** [comment]
I took that as a challenge.
https://github.com/hexahigh/dht-to-dce

**Comment by slatinsky** [comment]
Hello, it you find any issues with DCEF when it tries to parse your converted JSON export, let me know. Because it sometimes expects some fields to always be present. [Roachbones/discordless](https://github.com/Roachbones/discordless) also needed some fixes from my side

**Comment by hexahigh** [comment]
Alright, will do.

**Comment by hexahigh** [comment]
Closing this as everything works as intended
