### ISSUE TITLE
Attached files are not shown

### ISSUE THREAD

**Issue by slatinsky** [slatinsky/DiscordChatExporter-frontend#47]
### Discussed in https://github.com/slatinsky/DiscordChatExporter-frontend/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **Oguret2** December  3, 2023</sup>
Attached files are not displayed. There are no problems with attached photos or videos, but other files are not displayed at all. There are files in the attachment folder and they are listed in the chat json. Add the ability to display files of any format plz.
![yAwWN0NKak](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/152782570/779742ad-603d-4ec5-8f61-7b6668dd22ff)
![bGZRmTWGG9](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/152782570/54032402-3f47-4f4f-a2f2-7698b76f5b95)
</div>

**Comment by Oguret2** [comment]
If needed I can provide more screenshots.

**Comment by slatinsky** [comment]
Hello, thank you for your issue report. I don't need more screenshots.
I am currently improving markdown message parser, so I will create build for this regression after that is fully done.

**Comment by slatinsky** [comment]
Hello, the issue was fixed in the referenced commit. Thank you for your issue report <3

You can download beta build from [actions](https://github.com/slatinsky/DiscordChatExporter-frontend/actions) tab while logged into Github. Or if you use docker, pull the updated image
