### ISSUE TITLE
Http-Server.exe detected as Malware / Trojan

### ISSUE THREAD

**Issue by NeikiDev** [slatinsky/DiscordChatExporter-frontend#56]
File detected:

```
\DiscordChatExporter-frontend-v2.9.0-win\dcef\backend\http-server\http-server.exe
```

Version:
```
DiscordChatExporter-frontend-v2.9.0-win
```

Proof / Info:
https://tip.neiki.dev/file/823cf5738baff045fa71783fd1f2f5f7656f0e1d99518ccb57c479824eaef763
https://www.virustotal.com/gui/file/823cf5738baff045fa71783fd1f2f5f7656f0e1d99518ccb57c479824eaef763
https://opentip.kaspersky.com/823cf5738baff045fa71783fd1f2f5f7656f0e1d99518ccb57c479824eaef763/results

**Comment by NeikiDev** [comment]
Zip Scan:
https://www.virustotal.com/gui/file/e44a85ae4939c01fb7d1e958248da51efeb7f179f539e16ff848174677733cc7/

File detected and was deleted by Kaspersky Antivirus. 

FP?

**Comment by slatinsky** [comment]
That looks like it is false positive.

Here is a build process:
https://github.com/slatinsky/DiscordChatExporter-frontend/blob/main/.github/workflows/windows-build.yml

Binaries in the releases are exactly the same as binaries built by github actions:
https://github.com/slatinsky/DiscordChatExporter-frontend/actions

**Comment by NeikiDev** [comment]
Yes, i also wondered because it looks like to me that your just using the official http-server package build to an exe.

I submitted that case to Kaspersky directly and forwarded it.

Thanks for the answer, if you got any new information or anything related please let me know so i can add that!

**Comment by slatinsky** [comment]
Thanks you <3. I have security alerts enabled and there has not been an issue with http-server.

**Comment by NeikiDev** [comment]
Hey, i have good updates.

Kaspersky Lab messaged me back and resolved the false positive detection!

My own comment / vote / report will also be fixed very soon!

Thanks for the cooperation and fast reply to help resolve this issue faster.

https://www.virustotal.com/gui/file/e44a85ae4939c01fb7d1e958248da51efeb7f179f539e16ff848174677733cc7/
https://www.virustotal.com/gui/file/823cf5738baff045fa71783fd1f2f5f7656f0e1d99518ccb57c479824eaef763

**Comment by slatinsky** [comment]
Thank you for your help too <3. Closing the issue
