### ISSUE TITLE
Brackets not rendering correctly/deleting messages

### ISSUE THREAD

**Issue by Thinker109** [slatinsky/DiscordChatExporter-frontend#57]
In our discord server we tend to use brackets for a lot of [actions] [or thoughts] in-character. The exporter seems to handle one set of brackets per message fine but deletes text if you have more than one per message. Example images down below:

(but if they don't load and example would be something like:)

On Discord: [brackets] 
On ChatExporter: [brackets] 

On Discord: [brackets] [2] [3] [last one]
On ChatExporter: brackets 3 (<- and the text is colored blue)

## Steps to reproduce the problem

This is a consistent problem across channels. Not sure how to circumvent it. Markdown doesn't seem to be the issue as I've also tried it with Format Markdown disabled. (Though maybe that didn't work, either, since italics still show up..?)

## Specifications
![image](https://github.com/user-attachments/assets/a3d38bd9-d8fd-4929-80e2-8da28220d6da)
![image](https://github.com/user-attachments/assets/18300dbe-f1a8-47f2-9a3b-6e497fde9a59)

### Environment

  - Operating system: Windows 10
  - CPU Architecture: AMD64
  - Flavor: Windows binary release (i believe)

### DiscordChatExporter-frontend

  - [Release](https://github.com/slatinsky/DiscordChatExporter-frontend/releases) version or commit hash: v2.9.0
  - Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?: Don't know

### [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)

- Version (CLI `--version`): v2.43.3.

How did you export the data?
  - Export format (CLI `--format`): Json 
  - Downloaded assets (CLI `--media`): Yes
  - Markdown processing (CLI `--markdown`): Yes and No (two tries)
  - Other CLI options (optional): ...

**Comment by slatinsky** [comment]
Hello,

Thanks for the report <3
That's a bug with my markdown renderer - it probably thinks that the brackets are a markdown link.

Your exports are fine (but I suggest exporting with markdown disabled in DiscordChatExporter). After this issue is fixed, you won't need to re-download your exports again, you will just update DiscordChatExporter-frontend. 

I am quite busy now IRL, but parser improvements are being worked on in (work in progress) newfrontend branch. This will be the next big DiscordChatExporter-frontend update :).

**Comment by Thinker109** [comment]
Hi! Thanks for your quick response. Unfortunately, as I mentioned in my original post it seems like there's no difference between markdown-off or markdown-on? I hit the button and it still renders the markdown (italics, brackets, etc) in the DCEF. Any idea what I can do in the meantime to fix that? If not, I'll just wait for the update! Thank you very much once again for this project: absolute lifesaver

**Comment by slatinsky** [comment]
Hello, the issue has been fixed in the latest commit. Try the new [beta build](https://github.com/slatinsky/DiscordChatExporter-frontend/actions/runs/10434762183) :)
