### ISSUE TITLE
Is this only for server chats?

### ISSUE THREAD

**Issue by SladeHazard** [slatinsky/DiscordChatExporter-frontend#58]
The name is a bit misleading would you better if you changed it or add a disclaimer in the read me of the github page stating that this does not support PRIVATE DM viewing, as I came from discordchatexporter which lets you export dms as well and I wanted to view them.

**Comment by slatinsky** [comment]
Hello, it supports DMs. They show at the "home page". The demo does not have an example export of direct message conversation, but the functionality is there

**Comment by SladeHazard** [comment]
> Hello, it supports DMs. They show at the "home page". The demo does not have an example export of direct message conversation, but the functionality is there

hey, is it possible to know how to do this? for me the exported dm's do not show up at all..

![image](https://github.com/user-attachments/assets/1277a787-7f90-47bf-ac91-b175d53a6a1b)


![image](https://github.com/user-attachments/assets/7aaa7dca-a1f6-4953-bba6-75a9142e103d)

**Comment by SladeHazard** [comment]
only the example guild is showing up for me even though i already deleted it from the exports folder & restarted

![image](https://github.com/user-attachments/assets/17f63ad7-8b0b-4796-82d8-9457e4e5bfe2)


also i deleted that csv file that didnt fix it

**Comment by slatinsky** [comment]
Html exports are not supported in this viewer. Just double click them to view them in your browser :).

To view your exports in this viewer, you need to export in json format. Follow docs in README.md for instructions, how to do it

**Comment by slatinsky** [comment]
Closing this issue, the question has been answered
