### ISSUE TITLE
gray screen uncaught error and not found

### ISSUE THREAD

**Issue by TarikHaci** [slatinsky/DiscordChatExporter-frontend#6]
Dear programmer, your project is so professional and everthing included I love it.

But unfortunatelly the front-end project didnt work fully.
So I installed: [DiscordChatExporter-frontend-v1.13.0-win.zip](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/download/v1.13.0/DiscordChatExporter-frontend-v1.13.0-win.zip)
And then I extracted it.
And I put JSON export of the DiscordChatExporter made by GUI in the exports directory.
But I cant see anything still.
Error: https://prnt.sc/yW4dex1TBZqU
Exports included: https://prnt.sc/CaBZOB2VAfsu

Any reason why and how to fix?

**Comment by slatinsky** [comment]
Hello,

thanks for raising an issue. I need help from you, because I can't replicate the issue with my exports.

Can you please provide me preprocess logs?:
1. navigate to folder, where START_VIEWER.bat is located
2. press alt+d to highlight address bar
3. type in `cmd` and press enter
4. in the command line (black box) type in `START_VIEWER.bat`
5. remove / blur sensitive data and send me the log

If you can, can you please provide me with your DiscordChatExporter version you used to create an export?
a) If you used command line version of DiscordChatExporter , run `DiscordChatExporter.Cli.exe --version` to get version
b) if you used GUI version - the version number is in the window name - `DiscordChatExporter vX.XX.X`

thank you

also major rewrite is in progress in dev branch, but I will fix major issues like these in current version

**Comment by TarikHaci** [comment]
Major thanks to your quick and good quality response. I found out the issue after I tried to zip the export directory for you.
Appearntly the channel had the emoji "💬 Da'wah", Windows can't handle.

Maybe it will be useful the message I was preparing meanwhile before I realized the cause of the error:
CMD:
`C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0>START_VIEWER.bat

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0>pushd "C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\"

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0>cd dcef/backend/preprocess

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\preprocess>preprocess.exe ../../../exports/ temp/
Running compiled version of preprocess.py
Found 1 JSON files
Found 0 HTML files

Found 29 media files

Hash file does not exist
Hash is different, cache is not up to date
   Downloading ggsans-normal-400.woff2
   Downloading ggsans-italic-400.woff2
   Downloading ggsans-normal-500.woff2
   Downloading ggsans-italic-500.woff2
   Downloading ggsans-normal-600.woff2
   Downloading ggsans-italic-600.woff2
   Downloading ggsans-normal-700.woff2
   Downloading ggsans-italic-700.woff2
   Downloading ggsans-normal-800.woff2
   Downloading ggsans-italic-800.woff2

Sorting JSONs by guild_id...
   done

Getting channels and categories sort...
   Could not find any channel_info.json, channels and categories won't be sorted
Processing HTML...
   Found 0 message ids in HTML files

Processing guild 'Waarom islam?'
Step 0 - Reading data from json files...
   done
Step 1 - Finding deleted messages...
   Found 0 deleted messages
Step 2 - Recreating forums and missing channels from threads...
Step 3 - Sorting messages and channels...
   39 messages
   1 text channels
   0 voice channels
   0 threads or forum posts
   0 other channels
Step 4 - Deduplicating authors...
Step 5 - Deduplicating reactions...
Step 6 - Finding and preprocessing referenced local filenames...
Traceback (most recent call last):
  File "main.py", line 29, in <module>
  File "main.py", line 15, in main
  File "Preprocess.py", line 277, in process
  File "GuildPreprocess.py", line 572, in process
  File "GuildPreprocess.py", line 362, in calculate_local_filenames
  File "Assets.py", line 172, in fill_message_with_local_filenames
  File "Assets.py", line 147, in calculate_local_file_attributes
  File "Assets.py", line 119, in resolve_url_or_path
  File "Assets.py", line 29, in get_filepath
FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: "../../../exports/Waarom islam_ - 💬 Da'wah - gods-bewijs [927760743296823296].json_Files/human-footprints-in-the-snow-under-sunligh-DB44D.png"
[24332] Failed to execute script 'main' due to unhandled exception!

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\preprocess>cd ../nginx

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>if not exist logs mkdir logs

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>if not exist temp mkdir temp

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>start "nginx" nginx.exe -c .\conf\nginx-prod.conf

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>timeout /t 1 /nobreak  1>nul

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>if exist "C:\Program Files\Google\Chrome\Application\chrome.exe" (start "" "C:\Program Files\Google\Chrome\Application\chrome.exe" --app="http://127.0.0.1:21011/" --enable-precise-memory-info )  else (if exist "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" (start "" "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --app="http://127.0.0.1:21011/" --enable-precise-memory-info )  else (start "" rundll32 url.dll,FileProtocolHandler http://127.0.0.1:21011/ ) )

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0\dcef\backend\nginx>cd ../../../

C:\Users\BLUR\Export_Dashboard_JSON\DiscordChatExporter-frontend-v1.13.0>
`
I used the GUI DiscordChatExporter v2.36.4
https://prnt.sc/ytoNmNVh29vW
And this was my export option:
https://prnt.sc/1lNsSsf--RL3
You can find the export data here:
... (not need because I realised here the problem)

**Comment by TarikHaci** [comment]
I would like to suggest if you have time and have plans to make the project more user friendly, to also include copy button to copy multiple messages including the ** ** (bold) and other styling of the message, because now when I copy from this front-end I need to set bold/italic and so on myself.

Thanks in advance.

**Comment by slatinsky** [comment]
The latest [release v1.13.1](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v1.13.1) should fix your issue
