### ISSUE TITLE
Hey! Does this support threads?

### ISSUE THREAD

**Issue by EDLLT** [slatinsky/DiscordChatExporter-frontend#61]
Really, the question is in the title
Does it support viewing threads as well?

**Comment by slatinsky** [comment]
Hello, yes it supports threads and forum posts

**Comment by EDLLT** [comment]
Thank you for your prompt response!

**Comment by EDLLT** [comment]
> Hello, yes it supports threads and forum posts 

Hey so, I used the dce gui on windows to select all channels in my discord server then exported it in json(my pc runs on a Linux distro but I tried this first on a friend's windows laptop)

Using dce-f, I see that there were threads, but I have no way to access these threads. Am I supposed to export it using the dce cli instead of the dce gui to get the threads?

**Comment by EDLLT** [comment]
Hey @slatinsky 
Apologies for the many questions

``--markdown false``
Why should markdown be disabled and what are the consequences of enabling it?
