### ISSUE TITLE
NGINX not starting

### ISSUE THREAD

**Issue by Cronadax** [slatinsky/DiscordChatExporter-frontend#7]
`2022/12/30 10:14:07 [emerg] 11632#3000: unknown "discord" variable
2022/12/30 10:14:32 [emerg] 7976#5340: unknown "discord" variable
2022/12/30 10:15:48 [emerg] 11480#6832: unknown "discord" variable
2022/12/30 10:18:49 [emerg] 9884#9888: unknown "discord" variable
2022/12/30 10:19:07 [emerg] 3364#3368: unknown "discord" variable
2022/12/30 10:19:58 [emerg] 3020#8440: unknown "discord" variable`
This is what the error.log contains inside the nginx>logs
I tried disabling the antivirus and also the older version, but I always get a blank page with microsoft edge:
![image](https://user-images.githubusercontent.com/121682029/210086596-e1fbf35b-6869-4ec7-a878-49f204c947fb.png)
Thank you for the effort creating such tool, I would be vare greateful if you can help me.

**Comment by slatinsky** [comment]
Hello,

the "website" won't run in edge, if the nginx webserver is not running correctly.

I can't reproduce your issue with information you provided, so we can try few debugging steps:
1. did you download latest release from [https://github.com/slatinsky/DiscordChatExporter-frontend/releases](https://github.com/slatinsky/DiscordChatExporter-frontend/releases)? Or are you running from source? Or are you using docker version?
2. are you running `nginx` by running `START_VIEWER.bat`?

3.
- navigate to folder `dcef/backend/nginx`
- press alt+d to highlight address bar
- type in `cmd` and press enter
- type `where nginx` and confirm, that the version from current directory is being used, not globally installed version
- type `winver` and tell me your Windows version

4. can you try stable version of nginx?
- download stable version nginx/Windows-1.22.1 [http://nginx.org/en/download.html](http://nginx.org/en/download.html)
- replace binary in `dcef/backend/nginx/nginx.exe` with version from the archive
- run `START_VIEWER.bat`



If nothing works, you can use as workaround old version [v1.9.0](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v1.9.0) that doesn't use nginx yet. But you won't get all new features and bugfixes from newer versions.

**Comment by Cronadax** [comment]
Thanks a lot for the response, yes I know it's hard to understand why, anyway here are the things you asked me:
1. Yes, I'm suing the last release
2. I run the START_VIEWER.bat but I see no CMD window of nginx
3. Verified that is using the nginx in the folder and not a global installed one
3.1. Windows 10 21H2 OS Build 19044.2364
5. log:
`Microsoft Windows [Version 10.0.19044.2364]
(c) Microsoft Corporation. All rights reserved.

G:\DiscordChatExporter-frontend-v1.13.1-win>START_VIEWER.bat

G:\DiscordChatExporter-frontend-v1.13.1-win>pushd "G:\DiscordChatExporter-frontend-v1.13.1-win\"

G:\DiscordChatExporter-frontend-v1.13.1-win>cd dcef/backend/preprocess

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\preprocess>preprocess.exe ../../../exports/ temp/
Running compiled version of preprocess.py
Found 112 JSON files
Found 13 HTML files

Found 2833 media files

Hash: c9f206b40d33bb163cc5f3146fd581194e1cede655c0882aa6cda54bda963232
Hash is the same, cache is up to date

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\preprocess>cd ../nginx

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>if not exist logs mkdir logs

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>if not exist temp mkdir temp

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>start "nginx" nginx.exe -c .\conf\nginx-prod.conf

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>timeout /t 1 /nobreak  1>nul

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>if exist "C:\Program Files\Google\Chrome\Application\chrome.exe" (start "" "C:\Program Files\Google\Chrome\Application\chrome.exe" --app="http://127.0.0.1:21011/" --enable-precise-memory-info )  else (if exist "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" (start "" "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --app="http://127.0.0.1:21011/" --enable-precise-memory-info )  else (start "" rundll32 url.dll,FileProtocolHandler http://127.0.0.1:21011/ ) )

G:\DiscordChatExporter-frontend-v1.13.1-win\dcef\backend\nginx>cd ../../../

G:\DiscordChatExporter-frontend-v1.13.1-win>`

**Comment by slatinsky** [comment]
Weird, it should work based on your description.

I have tried to run DiscordChatExporter-frontend v1.13.1 release in fully updated clean install of Windows 10 to detect possible misconfiguration on my machine.

And it works on it (version 22h2 build 19045.2364 - the same version you provided). I only got firewall prompt that I had to accept. So probably something on your machine is preventing it from running.

Sorry, I am out of ideas how to help you with this binary release. If you somehow fix it, please write back. You can use docker version in WSL 2 instead.

---------------------
I also tested it on Windows 7 and nginx worked there too. (converted python binary (preprocess.exe) didn't run due to missing dlls, but it is not worth it to support end-of-life operating system)

**Comment by Cronadax** [comment]
Thanks anyway, can it be caused by the fact I have some python libraries installed like Discord.py?

**Comment by Cronadax** [comment]
I had some minutes before starting working so I tried on another laptop and it works, so I suppose it has something to do with my main laptop being fucked up lol

**Comment by slatinsky** [comment]
Closing the issue as stale. In the default configuration of Windows 10/11, nginx is working as intended.
